### ISSUE TITLE
repl doesn't see already defined variables

### ISSUE THREAD

**Issue by nickelghost** [adonisjs/adonis-cli#102]
Hello, I encountered a strange issue, where I could not use an already defined variable, because it was undefined, but I could not define it because it was already declared:
```
> let asd = Employee.findBy('login', 'superuser')
ReferenceError: Employee is not defined
    at repl:1:11
    at Script.runInContext (vm.js:74:29)
    at REPLServer.defaultEval (repl.js:250:29)
    at bound (domain.js:376:14)
    at REPLServer.runBound (domain.js:389:12)
> const Employee = use('App/Models/Employee')
undefined
> let asd = Employee.findBy('login', 'superuser')
SyntaxError: Identifier 'asd' has already been declared
    at repl:1:1
    at Script.runInContext (vm.js:74:29)
    at REPLServer.defaultEval (repl.js:250:29)
    at bound (domain.js:376:14)
    at REPLServer.runBound (domain.js:389:12)
> asd = Employee.findBy('login', 'superuser')
ReferenceError: asd is not defined
    at repl:1:5
    at Script.runInContext (vm.js:74:29)
    at REPLServer.defaultEval (repl.js:250:29)
    at bound (domain.js:376:14)
    at REPLServer.runBound (domain.js:389:12)
```

**Comment by thetutlage** [comment]
I don't think this is AdonisJs problem. It is simple Javascript scoping thing and the way `let` keyword works.

Checkout the screenshot, where an equivalent version of your code breaks in Chrome console too.

<img width="565" alt="screen shot 2018-04-30 at 5 32 32 pm" src="https://user-images.githubusercontent.com/1706381/39426208-8cb3f57e-4c9c-11e8-8545-48e8bff928cd.png">
