### ISSUE TITLE
Error when Foldername has Space Windows 10

### ISSUE THREAD

**Issue by cannap** [adonisjs/adonis-cli#72]
Hi when i have a Folder with space
when use **adonis serve --dev**
I get this error: 

```js 
C:\Arbeit Wichtig\amalyanshop>adonis serve --dev
┌──────────────────────┐
│                      │
│    Started server    │
│    Watcher: On       │
│    Debugger: Off     │
│                      │
└──────────────────────┘
module.js:473
      throw err;
      ^

Error: Cannot find module 'C:\Arbeit Wichtig\amalyanshop\"C:\Arbeit'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

**Comment by thetutlage** [comment]
Are you sure it's coz of that, since the error stack doesn't has much info

**Comment by cannap** [comment]
```
C:\test\with space\nospace\test>adonis serve --dev
┌──────────────────────┐
│                      │
│    Started server    │
│    Watcher: On       │
│    Debugger: Off     │
│                      │
└──────────────────────┘
module.js:473
      throw err;
      ^

Error: Cannot find module 'C:\test\with space\nospace\test\"C:\test\with'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
Application crashed, make sure to kill all related running process, fix the issue and re-run the app

```

no i rename "with space" to "withspace"
```
C:\test\withspace\nospace\test>adonis serve --dev
┌──────────────────────┐
│                      │
│    Started server    │
│    Watcher: On       │
│    Debugger: Off     │
│                      │
└──────────────────────┘
2017-11-10T10:06:18.117Z - info: serving app on http://127.0.0.1:3333
```

**Comment by thetutlage** [comment]
Okay seems like a bug. Will fix it

**Comment by RomainLanz** [comment]
Hey @cannap! 👋 

Which version of `Node.js` are you using?

**Comment by cannap** [comment]
npm 5.3.0
node 8.5.0

**Comment by thetutlage** [comment]
The issue is with nodemon directly. I am afraid, cannot help much here
